language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - xvfb

matrix:
  allow_failures:
    - python: "3.7"

notifications:
  email: false

before_install:
  - pip install cython  # for pypmc

install:
  - pip install .[sampling,plotting,testing]
  - pip install coveralls

script: nosetests --with-coverage --cover-package=flavio

after_success: coveralls
